src/main/java/org/zutjmx/apiservlet/webapp/headers/models/Carro.java
package org.zutjmx.apiservlet.webapp.headers.models;

import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import jakarta.inject.Inject;
import org.zutjmx.apiservlet.webapp.headers.configs.CarroCompra;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.logging.Logger;

@CarroCompra
public class Carro implements Serializable {
    private List<ItemCarro> items;

    @Inject
    private transient Logger logger;

    /*public Carro() {
        this.items = new ArrayList<>();
    }*/

    @PostConstruct
    public void inicializar() {
        this.items = new ArrayList<>();
        logger.info(":: Inicializando el carro de compras ::");
    }

    @PreDestroy
    public void destruir() {
        logger.info(":: Destruyendo el carro de compras ::");
    }

    public void addItemCarro(ItemCarro itemCarro) {
        if (items.contains(itemCarro)) {
            Optional<ItemCarro> optionalItemCarro = items
                                                    .stream()
                                                    .filter(i -> i.equals(itemCarro))
                                                    .findAny();
            if (optionalItemCarro.isPresent()) {
                ItemCarro i = optionalItemCarro.get();
                i.setCantidad(i.getCantidad()+1);
            }
        } else {
            this.items.add(itemCarro);
        }
    }

    public int getTotal() {
        return items.stream().mapToInt(ItemCarro::getImporte).sum();
    }

    public List<ItemCarro> getItems() {
        return items;
    }

    public void removeProductos(List<String> productoIds) {
        if (productoIds != null) {
            productoIds.forEach(this::removeProducto);
            // que es lo mismo a:
            // productoIds.forEach(productoId -> removeProducto(productoId));
        }
    }

    public void removeProducto(String productoId) {
        Optional<ItemCarro> producto = findProducto(productoId);
        producto.ifPresent(itemCarro -> items.remove(itemCarro));
    }

    public void updateCantidad(String productoId, int cantidad) {
        Optional<ItemCarro> producto = findProducto(productoId);
        producto.ifPresent(itemCarro -> itemCarro.setCantidad(cantidad));
    }

    private Optional<ItemCarro> findProducto(String productoId) {
        return  items.stream()
                .filter(itemCarro -> productoId.equals(Long.toString(itemCarro.getProducto().getId())))
                .findAny();
    }

}

src/main/java/org/zutjmx/apiservlet/webapp/headers/models/ItemCarro.java
package org.zutjmx.apiservlet.webapp.headers.models;

import org.zutjmx.apiservlet.webapp.headers.models.entities.Producto;

import java.util.Objects;

public class ItemCarro {
    private int cantidad;
    private Producto producto;

    public ItemCarro(int cantidad, Producto producto) {
        this.cantidad = cantidad;
        this.producto = producto;
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public int getImporte() {
        return cantidad*producto.getPrecio();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ItemCarro itemCarro = (ItemCarro) o;
        return Objects.equals(producto.getId(), itemCarro.producto.getId())
                && Objects.equals(producto.getNombre(), itemCarro.producto.getNombre());
    }

}

src/main/java/org/zutjmx/apiservlet/webapp/headers/models/entities/Categoria.java
package org.zutjmx.apiservlet.webapp.headers.models.entities;

import jakarta.persistence.*;

@Entity
@Table(name = "categorias")
public class Categoria {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String nombre;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}

src/main/java/org/zutjmx/apiservlet/webapp/headers/controllers/ActualizarCarroServlet.java
package org.zutjmx.apiservlet.webapp.headers.controllers;

import jakarta.inject.Inject;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import org.zutjmx.apiservlet.webapp.headers.models.Carro;

import java.io.IOException;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.List;

@WebServlet("/carro/actualizar")
public class ActualizarCarroServlet extends HttpServlet {

    @Inject
    private Carro carro;

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        //Se comenta para implementar CDI
        /*HttpSession session = req.getSession();
        if (session.getAttribute("carro") != null) {
            Carro carro = (Carro) session.getAttribute("carro");
            updateProductos(req, carro);
            updateCantidades(req, carro);
        }*/

        updateProductos(req, carro);
        updateCantidades(req, carro);

        resp.sendRedirect(req.getContextPath() + "/carro/ver");
    }

    private void updateProductos(HttpServletRequest request, Carro carro) {
        String[] deleteIds = request.getParameterValues("deleteProductos");

        if (deleteIds != null && deleteIds.length > 0) {
            List<String> productoIds = Arrays.asList(deleteIds);
            // Borramos los productos del carrito.
            carro.removeProductos(productoIds);
        }

    }

    private void updateCantidades(HttpServletRequest request, Carro carro) {

        Enumeration<String> enumer = request.getParameterNames();

        // Iteramos a traves de los parámetros y buscamos los que empiezan con
        // "cant_". El campo cant en la vista fueron nombrados "cant_" + productoId.
        // Obtenemos el id de cada producto y su correspondiente cantidad ;-).
        while (enumer.hasMoreElements()) {
            String paramName = enumer.nextElement();
            if (paramName.startsWith("cant_")) {
                String id = paramName.substring(5);
                String cantidad = request.getParameter(paramName);
                if (cantidad != null) {
                    carro.updateCantidad(id, Integer.parseInt(cantidad));
                }
            }
        }
    }
}

src/main/java/org/zutjmx/apiservlet/webapp/headers/controllers/AgregarCarroServlet.java
package org.zutjmx.apiservlet.webapp.headers.controllers;

import jakarta.inject.Inject;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.zutjmx.apiservlet.webapp.headers.configs.ProductoServicePrincipal;
import org.zutjmx.apiservlet.webapp.headers.models.Carro;
import org.zutjmx.apiservlet.webapp.headers.models.ItemCarro;
import org.zutjmx.apiservlet.webapp.headers.models.entities.Producto;
import org.zutjmx.apiservlet.webapp.headers.services.ProductoService;

import java.io.IOException;
import java.util.Optional;

@WebServlet("/carro/agregar")
public class AgregarCarroServlet extends HttpServlet {

    @Inject
    @ProductoServicePrincipal
    private ProductoService productoService;

    @Inject
    private Carro carro;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        Long id = Long.parseLong(req.getParameter("id"));

        /*Connection connection = (Connection) req.getAttribute("connection");
        ProductoService productoService = new ProductoServiceJdbcImpl(connection);*/

        Optional<Producto> producto = productoService.porId(id);
        if (producto.isPresent()) {
            ItemCarro itemCarro = new ItemCarro(1,producto.get());
            //Se comenta para implementar CDI
            /*HttpSession session = req.getSession();
            Carro carro = (Carro) session.getAttribute("carro");*/
            carro.addItemCarro(itemCarro);
        }
        resp.sendRedirect(req.getContextPath() + "/carro/ver");
    }
}

src/main/java/org/zutjmx/apiservlet/webapp/headers/controllers/LoginServlet.java
package org.zutjmx.apiservlet.webapp.headers.controllers;

import jakarta.inject.Inject;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import org.zutjmx.apiservlet.webapp.headers.models.entities.Usuario;
import org.zutjmx.apiservlet.webapp.headers.services.LoginService;
import org.zutjmx.apiservlet.webapp.headers.services.UsuarioService;

import java.io.IOException;
import java.util.Optional;

@WebServlet({"/login","/login.html"})
public class LoginServlet extends HttpServlet {

    @Inject
    private UsuarioService usuarioService;

    @Inject
    private LoginService loginService;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        //LoginService loginService = new LoginServiceSessionImpl();
        Optional<String> sessionOptional = loginService.getUsername(req);

        if (sessionOptional.isPresent()) {

            /*resp.setContentType("text/html;charset=UTF-8");
            try(PrintWriter out = resp.getWriter()) {
                out.println("<!DOCTYPE html>");
                out.println("<html>");
                out.println("    <head>");
                out.println("      <meta charset=\"UTF-8\">");
                out.println("      <title>Hola "+sessionOptional.get()+"</title>");
                out.println("    </head>");
                out.println("  <body>");
                out.println("      <h1>Hola "+sessionOptional.get()+" has iniciado sesión con éxito</h1>");
                out.println("      <p><a href=\"" + req.getContextPath() + "\">Regresar</a></p>");
                out.println("      <p><a href='" + req.getContextPath() + "/logout'>Cerrar sesión</a></p>");
                out.println("  </body>");
                out.println("</html>");
            }*/

            resp.sendRedirect(req.getContextPath() + "/welcome.jsp");
            
        } else {
            req.setAttribute("titulo",req.getAttribute("titulo") + ": Acceso");
            getServletContext().getRequestDispatcher("/login.jsp").forward(req, resp);
        }
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String username = req.getParameter("username");
        String password = req.getParameter("password");

        /*Connection connection = (Connection) req.getAttribute("connection");
        UsuarioService usuarioService = new UsuarioServiceImpl(connection);*/

        Optional<Usuario> usuarioOptional = usuarioService.login(username, password);

        if (usuarioOptional.isPresent()) {

            HttpSession session = req.getSession();
            session.setAttribute("username", username);

            resp.sendRedirect(req.getContextPath() + "/login.html");

        } else {
            resp.sendError(HttpServletResponse.SC_UNAUTHORIZED,"Usuario y/o contraseña no válidos.");
        }

    }
}

src/main/java/org/zutjmx/apiservlet/webapp/headers/controllers/LogoutServlet.java
package org.zutjmx.apiservlet.webapp.headers.controllers;

import jakarta.inject.Inject;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.*;
import org.zutjmx.apiservlet.webapp.headers.services.LoginService;
import org.zutjmx.apiservlet.webapp.headers.services.LoginServiceSessionImpl;

import java.io.IOException;
import java.util.Optional;

@WebServlet("/logout")
public class LogoutServlet extends HttpServlet {

    @Inject
    private LoginService loginService;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        //LoginService loginService = new LoginServiceSessionImpl();
        Optional<String> username = loginService.getUsername(req);

        if (username.isPresent()) {
            HttpSession session = req.getSession();
            session.invalidate();
        }

        resp.sendRedirect(req.getContextPath() + "/login.html");

    }
}

src/main/java/org/zutjmx/apiservlet/webapp/headers/controllers/ProductoEliminarServlet.java
package org.zutjmx.apiservlet.webapp.headers.controllers;

import jakarta.inject.Inject;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.zutjmx.apiservlet.webapp.headers.configs.ProductoServicePrincipal;
import org.zutjmx.apiservlet.webapp.headers.models.entities.Producto;
import org.zutjmx.apiservlet.webapp.headers.services.ProductoService;

import java.io.IOException;
import java.util.Optional;

@WebServlet("/productos/eliminar")
public class ProductoEliminarServlet extends HttpServlet {

    @Inject
    @ProductoServicePrincipal
    private ProductoService productoService;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        /*Connection connection = (Connection) req.getAttribute("connection");
        ProductoService productoService = new ProductoServiceJdbcImpl(connection);*/

        long id;
        try {
            id = Long.parseLong(req.getParameter("id"));
        } catch (NumberFormatException e) {
            id = 0L;
        }

        if (id > 0) {
            Optional<Producto> optionalProducto = productoService.porId(id);
            if (optionalProducto.isPresent()) {
                productoService.eliminar(id);
                resp.sendRedirect(req.getContextPath() + "/productos");
            } else {
                resp.sendError(HttpServletResponse.SC_NOT_FOUND,"No existe el producto con id: " + id);
            }
        } else {
            resp.sendError(HttpServletResponse.SC_NOT_FOUND,"El id del producto se debe de envíar como parámetro en la ruta URL.");
        }
    }
}

src/main/java/org/zutjmx/apiservlet/webapp/headers/controllers/ProductoServlet.java
package org.zutjmx.apiservlet.webapp.headers.controllers;

import jakarta.inject.Inject;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.zutjmx.apiservlet.webapp.headers.configs.ProductoServicePrincipal;
import org.zutjmx.apiservlet.webapp.headers.models.entities.Producto;
import org.zutjmx.apiservlet.webapp.headers.services.LoginService;
import org.zutjmx.apiservlet.webapp.headers.services.ProductoService;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

@WebServlet({"/productos", "/productos.html"})
public class ProductoServlet extends HttpServlet {

    @Inject
    @ProductoServicePrincipal
    private ProductoService productoService;

    @Inject
    private LoginService loginService;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        /*Connection connection = (Connection) req.getAttribute("connection");
        ProductoService productoService = new ProductoServiceJdbcImpl(connection);*/

        List<Producto> productos = productoService.listar();
        String servletPath = req.getServletPath();

        /*LoginService loginService = new LoginServiceSessionImpl();*/
        Optional<String> sessionOptional = loginService.getUsername(req);

        req.setAttribute("productos",productos);
        req.setAttribute("username",sessionOptional);
        req.setAttribute("titulo",req.getAttribute("titulo") + ": Listado Productos");

        getServletContext().getRequestDispatcher("/listar.jsp").forward(req,resp);

    }
}

src/main/java/org/zutjmx/apiservlet/webapp/headers/controllers/VerCarroServlet.java
package org.zutjmx.apiservlet.webapp.headers.controllers;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;

@WebServlet("/carro/ver")
public class VerCarroServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        req.setAttribute("titulo",req.getAttribute("titulo") + ": Carro de Compras");
        getServletContext().getRequestDispatcher("/carro.jsp").forward(req,resp);
    }
}

src/main/webapp/about.jsp
<jsp:include page="layout/header.jsp" />

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Acerca de Jakarta EE</h5>
    <h6 class="card-subtitle mb-2 text-muted">Aplicaci&oacute;n contruida con Jakarta EE</h6>
    <p class="card-text">Se usaron varios componentes de Jakarta 9 EE</p>
    <a href="https://jakarta.ee/" target="_blank" class="card-link">P&aacute;gina de Jakarta EE</a>
    <a href="https://github.com/zutjmx" target="_blank" class="card-link">Github de @zutjmx</a>
  </div>
</div>

<jsp:include page="layout/footer.jsp" />

src/main/webapp/carro.jsp
<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix = "c" uri = "http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="layout/header.jsp" />
        <h3>${titulo}</h3>
        <c:choose>
            <c:when test="${carro.items.isEmpty()}">
                <div class="alert alert-info" role="alert">
                    No hay productos en el carro
                </div>
            </c:when>
            <c:otherwise>
                <form name="formcarro" action="${pageContext.request.contextPath}/carro/actualizar" method="post">
                    <table class="table table-striped table-hover">
                      <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Cantidad</th>
                        <th>Total</th>
                        <th>Borrar</th>
                      </tr>
                      <c:forEach items="${carro.items}" var="item">
                          <tr>
                            <td>${item.producto.id}</td>
                            <td>${item.producto.nombre}</td>
                            <td>${item.producto.precio}</td>
                            <td><input type="text" size="4" name="cant_${item.producto.id}" value="${item.cantidad}" /></td>
                            <td>${item.importe}</td>
                            <td><input type="checkbox" value="${item.producto.id}" name="deleteProductos" /></td>
                          </tr>
                      </c:forEach>
                      <tr>
                        <td colspan="5" style="text-align: right">Total</td>
                        <td>${carro.total}</td>
                      </tr>
                    </table>
                    <a class="btn btn-primary" href="javascript:document.formcarro.submit();">Actualizar</a>
                </form>
            </c:otherwise>
        </c:choose>
        <div class="my-2">
            <a class="btn btn-sm btn-info" href="${pageContext.request.contextPath}/productos">Seguir comprando</a>
            <a class="btn btn-sm btn-secondary" href="${pageContext.request.contextPath}/index.jsp">Regresar</a>
        </div>
<jsp:include page="layout/footer.jsp" />

src/main/webapp/form-producto.jsp
<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" import="java.time.format.*"%>
<%@ taglib prefix = "c" uri = "http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="layout/header.jsp" />
        <h3>${titulo}</h3>
        <form action="${pageContext.request.contextPath}/productos/form" method="post">
            <div class="row mb-2">
                <label for="nombre" class="col-form-label col-sm-2">Nombre</label>
                <div class="col-sm-4">
                    <input type="text" name="nombre" id="nombre" class="form-control" maxlength="50" value="${producto.nombre}">
                </div>
                <c:if test="${errores != null && errores.containsKey('nombre')}">
                    <div class="alert alert-danger" role="alert">${errores.nombre}</div>
                </c:if>
            </div>

            <div class="row mb-2">
                <label for="precio" class="col-form-label col-sm-2">Precio</label>
                <div class="col-sm-4">
                    <input type="number" name="precio" id="precio" class="form-control" value="${producto.precio > 0 ? producto.precio: ""}">
                </div>
                <c:if test="${errores != null && not empty errores.precio}">
                    <div class="alert alert-danger" role="alert">${errores.precio}</div>
                </c:if>
            </div>

            <div class="row mb-2">
                <label for="sku" class="col-form-label col-sm-2">Sku</label>
                <div class="col-sm-4">
                    <input type="text" name="sku" id="sku" class="form-control" maxlength="10" value="${producto.sku}">
                </div>
                <c:if test="${errores != null && errores.containsKey('sku')}">
                    <div class="alert alert-danger" role="alert">${errores.sku}</div>
                </c:if>
            </div>

            <div class="row mb-2">
                <label for="fecha_registro" class="col-form-label col-sm-2">Fecha Registro</label>
                <div class="col-sm-4">
                    <input type="date" name="fecha_registro" id="fecha_registro" class="form-control" value="${producto.fechaRegistro != null? producto.fechaRegistro.format(DateTimeFormatter.ofPattern("yyyy-MM-dd")): ""}">
                </div>
                <c:if test="${errores != null && errores.containsKey('fecha_registro')}">
                    <div class="alert alert-danger" role="alert">${errores.fecha_registro}</div>
                </c:if>
            </div>

            <div class="row mb-2">
                <label for="categoria" class="col-form-label col-sm-2">Categoria</label>
                <div class="col-sm-4">
                    <select name="categoria" id="categoria" class="form-select">
                        <option value="">-- Seleccionar --</option>
                        <c:forEach items="${categorias}" var="categoria">
                        <option value="${categoria.id}" ${categoria.id.equals(producto.categoria.id)?"selected":""}>${categoria.nombre}</option>
                        </c:forEach>
                    </select>
                </div>
                <c:if test="${errores != null && errores.containsKey('categoria')}">
                    <div class="alert alert-danger" role="alert">${errores.categoria}</div>
                </c:if>
            </div>

            <div class="row mb-2">
                <div>
                    <input type="submit" value="${producto.id!=null && producto.id>0?"Guardar":"Crear"}" class="btn btn-primary">
                </div>
            </div>

            <input name="id" type="hidden" value="${producto.id}">
        </form>
        <a class="btn btn-sm btn-secondary" href="<%=request.getContextPath()%>">Regresar</a>
<jsp:include page="layout/footer.jsp" />

src/main/webapp/index.jsp
<jsp:include page="layout/header.jsp" />
        <h3>${titulo}</h3>
        <ul class="list-group">
            <li class="list-group-item active">
                Men&uacute; de Opciones
            </li>
            <li class="list-group-item">
                <a class="nav-link" href="${pageContext.request.contextPath}/productos">Listado de productos</a>
            </li>
            <li class="list-group-item">
                <a class="nav-link" href="${pageContext.request.contextPath}/login.html">Acceso</a>
            </li>
            <li class="list-group-item">
                <a class="nav-link" href="${pageContext.request.contextPath}/logout">Cerrar sesi&oacute;n</a>
            </li>
            <li class="list-group-item">
                <a class="nav-link" href="${pageContext.request.contextPath}/carro/ver">Ver Carro</a>
            </li>
        </ul>

<jsp:include page="layout/footer.jsp" />

src/main/webapp/listar.jsp
<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix = "c" uri = "http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="layout/header.jsp" />
        <h3>${titulo}</h3>
        <c:if test = "${username.present}">
            <div class="alert alert-info">Hola ${username.get()}, bienvenido</div>
            <a class="btn btn-info my-2" href="${pageContext.request.contextPath}/productos/form">[+] Nuevo Producto</a>
        </c:if>
        <button class="btn btn-danger my-2" id="btn" class="btn btn-primary">Prueba SweetAlert</button>
        <table class="table table-success table-hover table-striped">
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Categoría</th>
                <c:if test = "${username.present}">
                <th>Precio</th>
                <th>Agregar</th>
                <th>Editar</th>
                <th>Eliminar</th>
                </c:if>
            </tr>
            <c:forEach items="${productos}" var = "p">
            <tr>
                <td>${p.id}</td>
                <td>${p.nombre}</td>
                <td>${p.categoria.nombre}</td>
                <c:if test = "${username.present}">
                <td>${p.precio}</td>
                <td><a class="btn btn-sm btn-primary" href="${pageContext.request.contextPath}/carro/agregar?id=${p.id}">Agregar al Carro</a></td>
                <td><a class="btn btn-sm btn-success" href="${pageContext.request.contextPath}/productos/form?id=${p.id}">Editar Producto</a></td>
                <td><a class="btn btn-sm btn-danger" onClick="return confirm('Quiere eliminar?');" class="nav-link" href="${pageContext.request.contextPath}/productos/eliminar?id=${p.id}">Eliminar Producto</a></td>
                </c:if>
            </tr>
            </c:forEach>
        </table>
        <div class="my-2">
            <p>${applicationScope.mensaje}</p>
            <p>${requestScope.mensaje}</p>
            <a class="btn btn-sm btn-secondary" href="${pageContext.request.contextPath}">Regresar</a>
        </div>
<jsp:include page="layout/footer.jsp" />

src/main/webapp/login.jsp
<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<jsp:include page="layout/header.jsp" />
        <h3>${titulo}</h3>
        <form action="${pageContext.request.contextPath}/login" method="post">
            <div class="row my-2">
                <label for="username" class="form-label">Usuario</label>
                <div>
                    <input type="text" name="username" id="username" class="form-control">
                </div>
            </div>
            <div class="row my-2">
                <label for="password" class="form-label">Contraseña</label>
                <div>
                    <input type="password" name="password" id="password" class="form-control">
                </div>
            </div>
            <div class="row my-2">
                <div>
                    <input type="submit" value="Acceso" class="btn btn-primary">
                </div>
            </div>
        </form>
        <a class="btn btn-secondary" class="nav-link" href="index.jsp">Regresar</a>
<jsp:include page="layout/footer.jsp" />

src/main/webapp/welcome.jsp
<jsp:include page="layout/header.jsp" />
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Bienvenido</h5>
    <h6 class="card-subtitle mb-2 text-muted">Hola ${sessionScope.username}</h6>
    <p class="card-text">Has iniciado sesi&oacute;n con &eacute;xito.</p>
  </div>
</div>
<jsp:include page="layout/footer.jsp" />